Add function to get 3rd party name by application id.
solita/mnt-teet pull request #185
Opened 2021-01-22 15:09 UTC by aleksievelizhanin

Fix path to new Application response notification
Add 45 days to expire scheduled notification

2021-01-26 07:16 UTC, jkorpelin commented on app/backend/src/clj/teet/cooperation/cooperation_db.clj
> +(defn- is-date-after
This should be in the date util, and check if any of the existing fns could be used.

2021-01-26 07:17 UTC, jkorpelin commented on app/backend/src/clj/teet/cooperation/cooperation_db.clj
> +  (let [
Unecessary empty line in let

2021-01-26 09:33 UTC, tatut requested changes

2021-01-26 09:33 UTC, tatut commented on app/backend/src/clj/teet/cooperation/cooperation_db.clj
> +(defn applicaiton-3rd-party [db application-id]
typo in "applicaTIon"

2021-01-26 09:33 UTC, tatut commented on app/backend/src/clj/teet/cooperation/cooperation_db.clj
> +             :where [?third-party :cooperation.3rd-party/applications ?application]
Instead of filtering results, add where clause like
`[(< ?response-deadline ?days)]` and give the time as in parameter

2021-01-27 12:51 UTC, tatut requested changes
Add tests for notification

2021-01-27 12:51 UTC, tatut commented on app/backend/resources/datomic/ion-config.edn
> +            {:fn teet.notification.ion/notify
the teet.notification.ion namespace should be renamed to teet.notification.notification-ion
and the file notification_ion.clj to comply with regular naming convention

2021-01-27 12:51 UTC, tatut commented on app/backend/src/clj/teet/notification/ion.clj
> +     (map #(let [application-id (first %)
nothing is transacted here?

How are the notifications saved.

Also how to determine if a notification is already sent fo an application and avoid sending it again.

2021-01-28 06:44 UTC, tatut requested changes

2021-01-28 06:44 UTC, tatut commented on app/backend/src/clj/teet/notification/ion.clj
> +             (d/transact conn {:tx-data current-tx-data}))
Don't call transact in a map. Gather all info into one transaction data and transact it once.

2021-01-28 06:44 UTC, tatut commented on app/backend/src/clj/teet/notification/ion.clj
> +             (d/transact conn {:tx-data current-tx-data}))
And no need to call notify-tx-data as a transaction function, it isn't doing any constraint validation that needs to be atomic.

Instead consider:
```(t/transact conn {:tx-data (map (partial notify-tx-data) (cooperation-db/applications-to-be-expired db days))})```

2021-01-29 06:36 UTC, tatut commented on app/backend/test/teet/notification/notification_ion_test.clj
> +(ns teet.notification.notification-ion-test
mark this namespace with the `^:db` metadata

2021-01-29 07:35 UTC, tatut approved these changes

2021-01-29 07:46 UTC, merged