Teet-981 changes
solita/mnt-teet pull request #192
Opened 2021-01-27 11:42 UTC by solita-erkkiv

The new styles for meetings and links are missing but they can be created separately if needed.

2021-01-28 07:04 UTC, jkorpelin commented on app/frontend/src/cljs/teet/file/file_view.cljs
> +        ])]))
This shouldn't be it's own row

2021-01-28 07:05 UTC, jkorpelin commented on app/frontend/src/cljs/teet/file/file_view.cljs
> +        [:div {:class [(<class common-styles/flex-align-center)]}
does this work? I thought that you had to have :classes if you wanted to provide a list of classes to an element?

2021-01-28 07:08 UTC, jkorpelin commented on app/frontend/src/cljs/teet/link/link_view.cljs
> +   [:div {:style (merge {:flex :auto
this could be indented better, or better yet made into it's own class.

2021-01-28 07:18 UTC, jkorpelin reviewed
![image](https://user-images.githubusercontent.com/45553697/106103509-bd37f500-6149-11eb-9a92-f1f29926eaa7.png)

should the add decision look like this?

2021-01-28 07:24 UTC, jkorpelin commented on app/frontend/src/cljs/teet/meeting/meeting_view.cljs
> +                            child
Is all of this stuff necessary? At a quick glance I can't find a place where this component gets a component as a child. So some of these checks could be removed.

2021-01-28 07:40 UTC, jkorpelin commented on app/frontend/src/cljs/teet/ui/tabs.cljs
> +   :border-bottom "solid #005AA3 1px"})
these colors should come from theme-colors

2021-01-29 12:44 UTC, tatut commented on app/frontend/src/cljs/teet/meeting/meeting_view.cljs
> +              :meeting.agenda/keys [topic responsible body decisions file/_attached-to] :as agenda-topic} agenda]
Cant use `file/_attached-to` in `:meet.agenda/keys`... that would make the key `:meeting.agenda/file/_attached-to` which is not correct.

This needs to be as separate destructuring in the parent map.

2021-01-29 12:46 UTC, tatut requested changes
See destructuring problem in comment

2021-02-01 07:38 UTC, merged